# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactRedux' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactRedux

  

  platform :ios, '9.0'
  target 'ReactReduxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactRedux-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactRedux-tvOS

  target 'ReactRedux-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
